//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutokeyRPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPC_Telai
    {
        public int ID { get; set; }
        public int IDCantiere { get; set; }
        public string IDOperatore { get; set; }
        public int IDLotto { get; set; }
        public bool IsFinished { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string Telaio { get; set; }
        public string Descr { get; set; }
    
        public virtual AUK_cantieri AUK_cantieri { get; set; }
        public virtual RPC_Lotti RPC_Lotti { get; set; }
        public virtual RPC_Telai RPC_Telai1 { get; set; }
        public virtual RPC_Telai RPC_Telai2 { get; set; }
        public virtual PKT_Operatori PKT_Operatori { get; set; }
    }

    public partial class RPC_TelaiXModifica
    {
        public int ID { get; set; }

        public bool IsFinished { get; set; }

        public System.DateTime InsertDate { get; set; }


    }
}
